version: '3.3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: 'prometheus'
    ports:
      - '9090:9090'
    volumes:
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    #command: --config.file=/etc/prometheus/prometheus.yml

  grafana:
    build: './grafana'
    container_name: 'grafana'
    ports:
      - '3000:3000'
    links:
      - prometheus